Description:
  Made by Akshay Bhardwaj. 
  A script for network deployment for the app Udagram.

Parameters:
  EnvironmentName:
    Type: String
    Description: The name of the project that will be prefixed to every resource associated witht he project.

Resources:

  LoadBalancerSecGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security Group to control traffic to our Load Balancer
      VpcId:
        Fn::ImportValue:
          !Sub "${EnvironmentName}-VPCID"
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0
      Tags:
          - Key: Name
            Value: !Sub ${EnvironmentName} Load Balancer Security Group